apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: minio-k8s
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: Secret
        name: k10-minios3-secret
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      name: minios3-k10-bucket
      objectStoreType: S3
      endpoint: 'http://192.168.1.122'
      skipSSLVerify: true
      name: k10
      region: nl-home-lab-1
